name: Deploy Backend to Fly.io

on:
  push:
    branches:
      - main       # Automatic deploy on main branch push
  workflow_dispatch: # Manual trigger from Actions tab


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set Fly.io token
      - name: Set Fly.io Token
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: echo "Fly token set"

      # Step 3: Deploy to Fly.io
      - name: Deploy to Fly.io
        run: fly deploy --config ./backend/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
